Models/CacheKeys.cs
namespace cancel.Models
{
    public static class CacheKeys
    {
        public static string Entry { get { return "_Entry"; } }
        public static string CallbackEntry { get { return "_Callback"; } }
        public static string CallbackMessage { get { return "_CallbackMessage"; } }
        public static string Parent { get { return "_Parent"; } }
        public static string Child { get { return "_Child"; } }
        public static string DependentMessage { get { return "_DependentMessage"; } }
        public static string DependentCTS { get { return "_DependentCTS"; } }
        public static string Ticks { get { return "_Ticks"; } }
        public static string CancelMsg { get { return "_CancelMsg"; } }
        public static string CancelTokenSource { get { return "_CancelTokenSource"; } }
    }
}

Models/ErrorViewModel.cs
using System;

namespace cancel.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/IScopedService.cs
using System;

namespace cancel.Models
{
    public interface IScopedService
    {
        Guid GetGuid();
    } 
}

Models/ISingletonService.cs
using System;

namespace cancel.Models
{
    public interface ISingletonService
    {
        Guid GetGuid();
    } 
}

Models/ITransisionService.cs
using System;

namespace cancel.Models
{
    public interface ITransisionService
    {
        Guid GetGuid();
    } 
}

Models/SomeService.cs
using System;

namespace cancel.Models
{
    public class SomeService : ITransisionService, IScopedService, ISingletonService
    {
        private readonly Guid _id;

        public SomeService()
        {
            _id = Guid.NewGuid();
        }

        public Guid GetGuid()
        {
            return _id;
        }
    }
}

Controllers/CacheController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System.Threading.Tasks;
using cancel.Models;
//https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2
namespace cancel.Controllers
{
    public class CacheController : Controller
    {
        private readonly IMemoryCache _cache;

        public CacheController(IMemoryCache cache)
        {
            _cache = cache;
        }
        public IActionResult Index()
        {
          
            return View("Cache");
        }

        public IActionResult CacheTryGetValueSet()
        {
            DateTime cacheEntry;

            if (!_cache.TryGetValue(CacheKeys.Entry, out cacheEntry))
            {
                // key not in cache
                cacheEntry = DateTime.Now;
                // set cache option
                var cacheOptions = new MemoryCacheEntryOptions()
                .SetSlidingExpiration(TimeSpan.FromSeconds(10)); // time cache idle before removed

                // save data in cache
                _cache.Set(CacheKeys.Entry, cacheEntry, cacheOptions);
            }
            return View("Cache", cacheEntry);
        }

         public async Task<IActionResult> CacheGetOrCreateAsync()
        {
            var cacheEntry = await 
            _cache.GetOrCreateAsync(CacheKeys.Entry, entry =>
            {
                entry.SlidingExpiration = TimeSpan.FromSeconds(3);
                return Task.FromResult(DateTime.Now);
            });

            return View("Cache", cacheEntry);
        }

         public IActionResult CacheGet()
        {
            var cacheEntry = _cache.Get<DateTime?>(CacheKeys.Entry);

            return View("Cache", cacheEntry);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using cancel.Models;
using Microsoft.Extensions.Logging;
using System.Threading;

namespace cancel.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [ResponseCache(CacheProfileName = "Default")]
        public IActionResult About()
        {
            ViewData["Message"] = "Cache data.";
            ViewData["Cache"] = $"{Guid.NewGuid()} {DateTime.Now} Expires 30 second {DateTime.Now.AddSeconds(30)} ";
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<IActionResult> Slow(CancellationToken cancellationToken)
        {
            await Task.Delay(10000, cancellationToken);
            ViewData["message"] = "Task wait complete";
            return View();
        }
    
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

       
    }
}

Controllers/HostedController.cs
using Microsoft.AspNetCore.Mvc;

namespace cancel.Controllers
{
    public class HostedController
    {

        public HostedController()
        {
        }

        public ActionResult<int> Index()
        {
            return 1;
        }
    }
}

Controllers/ScopeController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using cancel.Models;

namespace cancel.Controllers
{
    public class ScopeController : Controller
    {
        private readonly ITransisionService _transisionService1;
        private readonly ITransisionService _transisionService2;
        private readonly IScopedService _scopedService1;
        private readonly IScopedService _scopedService2;
        private readonly ISingletonService _singletonService1;
        private readonly ISingletonService _singletonService2;

        public ScopeController(ITransisionService tran1, ITransisionService tran2,
        IScopedService scoped1, IScopedService scoped2, ISingletonService single1,
        ISingletonService single2)
        {
            _transisionService1 = tran1;
            _transisionService2 = tran2;
            _scopedService1 = scoped1;
            _scopedService2 = scoped2;
            _singletonService1 = single1;
            _singletonService2 = single2;
        }
        public IActionResult Index()
        {
            ViewBag.Transistion1 = $"First transision instance {_transisionService1.GetGuid().ToString()}";
            ViewBag.Transistion2 = $"Second transision instance {_transisionService2.GetGuid().ToString()}";
            ViewBag.Scope1 = $"First Scoped instance {_scopedService1.GetGuid().ToString()}";
            ViewBag.Scope2 = $"Second transision instance {_scopedService2.GetGuid().ToString()}";
            ViewBag.Singleton1 = $"First Singleton instance {_singletonService1.GetGuid().ToString()}";
            ViewBag.Singleton2 = $"Second Singleton instance {_singletonService2.GetGuid().ToString()}";
            return View();
        }
    }
}

Controllers/ServerSentEventController.cs
using System;
using System.Collections;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Threading;


namespace cancel.Controllers
{
    public class ServerSentEventController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public ServerSentEventController(IHttpContextAccessor _httpContextAccessor)
        {
            this._httpContextAccessor = _httpContextAccessor;
        }

       
        [HttpGet]
        public async Task GetTime(CancellationToken cancellationToken)
        {
            var response = _httpContextAccessor.HttpContext.Response;
            response.Headers.Add("Content-Type", "text/event-stream");
            response.StatusCode = 200;

            await response.WriteAsync($"data: {DateTime.Now}\r\r", cancellationToken);
            response.Body.Flush();
        }
        [HttpGet]
        public async Task GetFile(CancellationToken cancellationToken)
        {
            var response = _httpContextAccessor.HttpContext.Response;
            response.Headers.Add("Content-Type", "text/event-stream");
            response.StatusCode = 200;
            var fileContent = await System.IO.File.ReadAllTextAsync(@"data.txt");
           
            await response.WriteAsync($"data: {fileContent}\r\r", cancellationToken);
            response.Body.Flush();
        }

    }
}

Views/Cache/Cache.cshtml
@model DateTime?


<section>
    <h2>Action</h2>
    <ul>
        <li><a asp-controller="Cache" asp-action="CacheTryGetValueSet">CacheTryGetValueSet</a></li>
        <li><a asp-controller="Cache" asp-action="CacheGetOrCreateAsync">CacheGetOrCreateAsync</a></li>
        <li><a asp-controller="Cache" asp-action="CacheGet">CacheGet</a></li>
        <li><a asp-controller="Cache" asp-action="CacheTryGetValueSet">TryGetValue And Set</a></li>
    </ul>
</section>
<h3>Current Time: @DateTime.Now.TimeOfDay.ToString()</h3>
<h3>Cached Time: @(Model == null ? "No Cache Entry Found" : Model.Value.TimeOfDay.ToString())</h3>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "Cache";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>
<h3>@ViewData["Cache"]</h3>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "SSE Demo";
}
@section Scripts
{
    <script src='~/js/sse.js' defer></script>
}
<h2>@ViewData["Title"]</h2>

<span id="sseResult"></span>
<p>Content from file:</p>
<span id="fileContent"></span>
<hr>
<button class="btn btn-info" id="btnClosetime">Close Time Stream</button>
<button id="btnClosefile" class="btn btn-danger">Close File Stream</button>
<button id="btnStopService" class="btn btn-danger">Stop File Service</button>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Views/Home/Slow.cshtml
@{
    ViewData["Title"] = "Slow test";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>
<a href="https://andrewlock.net/using-cancellationtokens-in-asp-net-core-mvc-controllers/">Referrence link</a>

Views/Scope/Index.cshtml
@{
    ViewData["Title"] = "Dependency Scope";
}
<h1>Dependency Injection Scoped</h1>
<h3>Transition Services</h3>
@ViewBag.Transistion1 <br>
@ViewBag.Transistion2
<h3>Scoped Services</h3>
@ViewBag.Scope1 <br>
@ViewBag.Scope2
<h3>Singleton Services</h3>
@ViewBag.Singleton1 <br>
@ViewBag.Singleton2
<hr>
<p>Transient services are safest to create, as you always get the new instance. But, since they are created every time they will use more memory & Resources and can have the negative impact on performance if you too many of them.

Use Transient lifetime for the lightweight service with little or no state.

Scoped services service is the better option when you want to maintain state within a request.

Singletons are created only once and not destroyed until the end of the Application. Any memory leaks in these services will build up over time. Hence watch out for the memory leaks. Singletons are also memory efficient as they are created once reused everywhere.

Use Singletons where you need to maintain application wide state. Application configuration or parameters, Logging Service, caching of data is some of the examples where you can use singletons.</p>

<p>
    Be careful, while injecting service into another service with a different lifetime

Consider the example of Singleton Service, which depends on another Service which is registered with say the transient lifetime.

When the request comes for the first time a new instance of the singleton is created. It also creates a new instance of the transient object and injects into the Singleton service.

When the second request arrives the instance of the singleton is reused. The singleton already contains the instance of the transient service Hence it is not created again. This effectively converts the transient service into the singleton.

The services with the lower lifetime injected into service with higher lifetime would change the lower lifetime service to higher lifetime. This will make the debugging the application very difficult and should be avoided at all costs.

Hence, remember the following rules

    Never inject Scoped & Transient services into Singleton service.
    Never inject Transient services into scoped service

</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cancel</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">cancel</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Cache</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Server Sent Event</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Slow">Slow</a></li>
                    <li><a asp-area="" asp-controller="Scope" asp-action="Index">DI Scope</a></li>
                    <li><a asp-area="" asp-controller="Cache" asp-action="Index">In Memory Cache</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - cancel</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>